name: GHA CI

run-name: Testing ${{ github.ref_name }} by @${{ github.actor }}
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # python-version: "3.10"  # Uses .python-version file in repo root
          cache: "poetry"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Install pre-commit
      # run: python -m pip install pre-commit
        run: poetry add pre-commit

      - name: Pre-Commit
        run: poetry run pre-commit run --show-diff-on-failure --color=always --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # python-version: "3.10"  # Uses .python-version file in repo root
          cache: "poetry"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest

      - name: Register SSH key(s) for private dependencies
        # Make sure the @v0.8.0 matches the current version of the action
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest